

spring:
  application:
    name: blintec-backend
  datasource:
    url: jdbc:postgresql://localhost:5433/blintec
    username: blintec
    password: blintec123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8081
